services:
  grafana:
    build:
      context: ./
      dockerfile: Dockerfile
    image: ghcr.io/volkovlabs/app:latest
    environment:
      - GF_INSTALL_PLUGINS=marcusolsson-static-datasource
    ports:
      - 3000:3000/tcp
    volumes:
      - ./provisioning:/etc/grafana/provisioning
