services:
  grafana:
    build:
      context: ./
      dockerfile: Dockerfile
    image: ghcr.io/volkovlabs/app:latest
    entrypoint: /run.sh
    ports:
      - 3000:3000/tcp
    environment:
      - GF_DEFAULT_APP_MODE=development
      - GF_INSTALL_PLUGINS=marcusolsson-static-datasource
    volumes:
      - ./provisioning:/etc/grafana/provisioning
